ASPNET2/Models/ErrorViewModel.cs
using System;
using Microsoft.EntityFrameworkCore;
using MVC.Models;
using MVC.Data;

namespace ASPNET2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public bool TryDbModel()
        {
            return false;
        }
    }
}

ASPNET2/Models/Reservation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVC.Models
{
    public class Reservation
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public Room Room { get; set; }
        public DateTime Date { get; set; }
        [StringLength(50, ErrorMessage = "Wrong number of characters. Minimum: 1, Maximum: 50", MinimumLength = 1), Required(), Display(Name = "Name")]
        public string CustomersName { get; set; }
        [StringLength(50, ErrorMessage = "Wrong number of characters. Minimum: 1, Maximum: 50", MinimumLength = 1), Required(), Display(Name = "Last name")]
        public string CustomersLastName { get; set; }
        [Required(), EmailAddress, Display(Name = "Email address")]
        public string CustomersEmail { get; set; }
        [Required(), RegularExpression(@"^\+([0-9]{3} ){3}[0-9]{3}$", ErrorMessage = "Telephone number must be in format: +XXX XXX XXX XXX"), Display(Name = "Phone number")]
        public string CustomersPhone { get; set; }
        [StringLength(500, ErrorMessage = "Wrong number of characters. Maximum: 500", MinimumLength = 0), Display(Name = "Note")]
        public string CustomersNote { get; set; }
    }
}

/*
    Místnost (která je rezervována)
    Datum a čas rezervace
    Jméno zákazníka (1..50 znaků)
    Příjmení zákazníka (1..50 znaků)
    Email zákazníka
    Telefonní číslo ve formátu +XXX XXX XXX XXX
    Poznámka (nepovinná, 0..500 znaků)
*/

ASPNET2/Models/Room.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MVC.Data;
using Microsoft.AspNetCore.Mvc;

namespace MVC.Models
{
    public class Room
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [StringLength(50, ErrorMessage = "Wrong number of characters. Minimum: 1, Maximum: 50", MinimumLength = 1), Required()]
        public string Name { get; set; }
        [StringLength(500, ErrorMessage = "Wrong number of characters. Minimum: 50, Maximum: 500", MinimumLength = 50), Required()]
        public string Description { get; set; }
        [Required(), Display(Name = "Opening at")]
        public int OpeningAt { get; set; }
        [Required(), Display(Name = "Closing at")]
        public int ClosingAt { get; set; }

        public List<Reservation> Reservations { get; set; }
    }
}


/*
    Název (povinný, řetězec o délce 1..50 znaků)
    Popis (povinný, řetězec o délce 50..500 znaků)
    Otevírací doba od (povinný, číslo vyjadřující hodinu od kdy je místnost otevřena a je možné vytvářet rezervace, tedy např. číslo 11 znamená, že místnost je otevřena od 11:00)
    Otevírací doba do (analogicky k otevírací době od, tedy např. 22 znamená, že místnost je možné rezervovat do 22:00)
    Vazba na rezervace uskutečněné na danou místnost (vizte dále)
*/

ASPNET2/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVC.Services;
using Newtonsoft.Json;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MVC.Controllers
{
    public class ApiController : Controller
    {
        IRoomService _service;

        public ApiController(IRoomService service)
        {
            _service = service;
        }

        [HttpGet("{year, month, day}")]
        public string Get(int year, int month, int day)
        {
            return JsonConvert.SerializeObject(_service.GetRoomsWithFreeHours(year, month, day), Formatting.Indented);
        }

        [HttpGet("{id, year, month, day}")]
        public string Get(int id, int year, int month, int day)
        {
            return JsonConvert.SerializeObject(_service.GetRoomWithFreeHours(id, year, month, day));
        }
    }
}

ASPNET2/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ASPNET2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC.Data;
using MVC.Models;
using MVC.Services;

namespace MVC.Controllers
{
    public class ReservationsController : Controller
    {
        IReservationService _reservationService;
        IRoomService _roomService;

        public ReservationsController(IReservationService reservationService, IRoomService roomService)
        {
            _reservationService = reservationService;
            _roomService = roomService;
        }

        [HttpGet]
        public IActionResult Create(int roomId)
        {
            ViewBag.Room = _roomService.GetById(roomId);
            return View();
        }

        [HttpPost]
        public IActionResult Create([Bind("Date")] Reservation reservation, int roomId, int hour)
        {
            reservation.Date = reservation.Date.AddHours(hour);
            return RedirectToAction("CustomerDetails", new { date = reservation.Date, roomId = roomId });
        }

        [HttpGet]
        public IActionResult CustomerDetails(DateTime date, int roomId)
        {
            Reservation reservation = new Reservation() { Date = date, Room = _roomService.GetById(roomId) };
            return View(reservation);
        }

        [HttpPost]
        public IActionResult CustomerDetails([Bind("CustomersName,CustomersLastName,CustomersEmail,CustomersPhone,CustomersNote")] Reservation reservation, int roomId, DateTime date)
        {
            reservation.Room = _roomService.GetById(roomId);
            reservation.Date = date;
            if(!ModelState.IsValid) return View(reservation);
            int? reservationId = _reservationService.Save(reservation);
            //If save to database wasnt successful
            if (reservationId == null) return View("Error");
            return RedirectToAction("Created", new { reservationId = reservationId });
        }

        [HttpGet]
        public IActionResult Created(int reservationId)
        {
            return View(_reservationService.GetById(reservationId));
        }

        public JsonResult FreeHours(int roomId, int year, int month, int day)
        {
            return new JsonResult(_roomService.GetFreeHours(roomId, year, month, day));
        }
    }
}

ASPNET2/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ASPNET2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC.Data;
using MVC.Models;
using MVC.Services;

namespace MVC.Controllers
{
    public class RoomsController : Controller
    {
        IRoomService _roomService;

        public RoomsController(IRoomService roomService)
        {
            _roomService = roomService ;
        }

        // GET: Rooms
        public async Task<IActionResult> Index()
        {
            return View(await _roomService.GetAll().ToListAsync());
        }
    }
}

ASPNET2/Views/Reservations/Create.cshtml
@model MVC.Models.Reservation

@{
    ViewData["Title"] = "Create";
    ViewBag.Hour = 0;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <script type="text/javascript">
        
    </script>
</head>
<body>

<h4>Booking for room: @ViewBag.Room.Name</h4>
<b>Room description:</b> @ViewBag.Room.Description
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" id="calendar-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" type="date" class="form-control" onchange="onCalendarChange(@ViewBag.Room.Id)" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Next" asp-route-roomId="@ViewBag.Room.Id" asp-route-hour="0" id="submit" class="btn btn-default" disabled="disabled" />
            </div>
        </form>
    </div>
    <div id="hours" class="col-md-4">
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Rooms">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

ASPNET2/Views/Reservations/Created.cshtml
@model MVC.Models.Reservation
@{
    ViewData["Title"] = "Created";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Created</h2>

<h3>Reservation</h3>
Room: @Model.Room.Name <br />
Time: @(Model.Date.ToString("dd.MM.yyyy")) @(Model.Date.ToString("H:mm")) - @(Model.Date.AddHours(1).ToString("H:mm")) <br />
For: @Model.CustomersName @Model.CustomersLastName <br />
<div>
    <a asp-action="Index" asp-controller="Rooms">Back to List</a>
</div>

ASPNET2/Views/Reservations/CustomerDetails.cshtml
@model MVC.Models.Reservation

@{
    ViewData["Title"] = "CustomerDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customer details</h2>

Booking room: @Model.Room.Name on @(Model.Date.ToString("dd.MM.yyyy")) @(Model.Date.ToString("H:mm")) - @(Model.Date.AddHours(1).ToString("H:mm"))
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CustomerDetails">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CustomersName" class="control-label"></label>
                <input asp-for="CustomersName" class="form-control" />
                <span asp-validation-for="CustomersName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomersLastName" class="control-label"></label>
                <input asp-for="CustomersLastName" class="form-control" />
                <span asp-validation-for="CustomersLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomersEmail" class="control-label"></label>
                <input asp-for="CustomersEmail" class="form-control" />
                <span asp-validation-for="CustomersEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomersPhone" class="control-label"></label>
                <input asp-for="CustomersPhone" class="form-control" />
                <span asp-validation-for="CustomersPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomersNote" class="control-label"></label>
                <input asp-for="CustomersNote" class="form-control" />
                <span asp-validation-for="CustomersNote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-route-date="@Model.Date" asp-route-roomId="@Model.Room.Id" type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Rooms" >Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASPNET2/Views/Rooms/Index.cshtml
@model IEnumerable<MVC.Models.Room>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OpeningAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ClosingAt)
                </th>
                <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model)
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @(item.Description.Length > 200 ? item.Description.Substring(0, 197) + "..." : item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OpeningAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClosingAt)
            </td>
            <td>
                <a asp-action="Create" asp-route-roomId="@(item.Id)" asp-controller="Reservations">Book now!</a>
            </td>
        </tr>
}
    </tbody>
</table>

ASPNET2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPNET2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Rooms" asp-action="Index" class="navbar-brand">ASPNET2</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ASPNET2</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>